# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50)),
                ('Salario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('Nome', models.CharField(max_length=50)),
                ('CRM', models.IntegerField(primary_key=True, serialize=False)),
                ('CPF', models.CharField(max_length=11)),
                ('Data_de_Nascimento', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Especialidade')),
            ],
        ),
    ]
